name: Vektor Sentinel Patrol

on:
  schedule:
    - cron: '*/15 * * * *' # Jalankan setiap 15 menit
  workflow_dispatch: # Tombol untuk menjalankan manual

jobs:
  hunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./modules/vektor-sentinel
        run: npm install

      - name: Execute Mission
        working-directory: ./modules/vektor-sentinel
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: node index.js